# Database trên Server (URL có th? khác localhost)

spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Các thông tin nh?y c?m b?t bu?c l?y t? môi tr??ng
app.security.jwt.secret-key=${JWT_SECRET_KEY:m3BtrDOYSPRJaQC+J7NdoONQ6gV1/978Yqoo15obL08=}
spring.mail.username=${MAIL_USERNAME:tvqqiyi@gmail.com}
spring.mail.password=${MAIL_PASSWORD:ebsk wlxv unac cwdt}
# Google OAuth2 Client ID
app.security.oauth2.google.client-id=${GOOGLE_CLIENT_ID:454804723745-hj4l1h9qdbpi9vcuducmc64f7g305s3i.apps.googleusercontent.com}