# MySQL Database cho Local (Ghi tr?c ti?p username/password n?u mu?n nhanh)
spring.datasource.url=jdbc:mysql://localhost:3306/systemvotting?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=190399

# Hi?n câu l?nh SQL ??p m?t d??i console ?? debug
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Các mã Secret dùng t?m ? máy local
app.security.jwt.secret-key=SlqjH9Pm07mazbnBnIfhBmifho7KzPC3yvAVIGYl3vw=
spring.mail.username=tvqqiyi@gmail.com
spring.mail.password=ebsk wlxv unac cwdt