
server.port=${PORT:10000}

# --- SERVER & TOMCAT TUNING FOR HIGH CONCURRENCY ---
server.tomcat.max-threads=1000
server.tomcat.max-connections=20000
server.tomcat.accept-count=1000
server.tomcat.connection-timeout=20000

# --- DATABASE CONNECTION POOL (HIKARICP) ---
spring.datasource.hikari.maximum-pool-size=150
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false


app.security.jwt.secret-key=${JWT_SECRET_KEY}


app.security.oauth2.google.client-id=${GOOGLE_CLIENT_ID}


sendgrid.api.key=${SENDGRID_API_KEY}


spring.mail.username=${MAIL_USERNAME}


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
# Redis
spring.data.redis.url=${SPRING_DATA_REDIS_URL}
