# TÃªn ?ng d?ng vÃ  Port c? ??nh
spring.application.name=SystemVotting

server.port=8080
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
# C?u hÃ¬nh JWT (Th?i gian h?t h?n th??ng c? ??nh)
app.security.jwt.expiration=900000

app.security.jwt.refresh-token.expiration=604800000

# C?u hÃ¬nh Mail chung (Host vÃ  Port c?a Gmail th??ng khÃ´ng ??i)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator (C?u hÃ¬nh chung ?? theo dÃµi h? th?ng)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# DÃ²ng nÃ y ?? ch?n mÃ´i tr??ng m?c ??nh khi b?n ?n Run trong IDE
