
spring.datasource.url=jdbc:mysql://localhost:3309/my_mysql_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Secrets & Credentials
app.security.jwt.secret-key=${JWT_SECRET_KEY}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Google OAuth2 Client ID
app.security.oauth2.google.client-id=${GOOGLE_CLIENT_ID}
# Thay vì dùng spring.redis.host
spring.data.redis.host=${redis_host}
spring.data.redis.port=${redis_port}


