# Môi trường Production (Cấu hình Docker)
spring.datasource.url=jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/${DB_NAME:systemvotting}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Secrets & Credentials
app.security.jwt.secret-key=${JWT_SECRET_KEY}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Google OAuth2 Client ID
app.security.oauth2.google.client-id=${GOOGLE_CLIENT_ID}
